import { Player } from "@/types/formation";

export const INITIAL_PLAYERS: Player[] = [
  {
    id: 1,
    name: "messi",
    position: "FW",
    number: 10,
    overall: 99,
    seasonType: "worldBest",
  },
  {
    id: 2,
    name: "ronaldo",
    position: "FW",
    number: 7,
    overall: 98,
    seasonType: "worldBest",
  },
  {
    id: 3,
    name: "neymar",
    position: "FW",
    number: 11,
    overall: 95,
  },
  {
    id: 4,
    name: "debruyne",
    position: "MF",
    number: 17,
    overall: 96,
  },
  {
    id: 5,
    name: "modric",
    position: "MF",
    number: 10,
    overall: 94,
  },
  {
    id: 6,
    name: "kante",
    position: "MF",
    number: 7,
    overall: 92,
  },
  {
    id: 7,
    name: "vandijk",
    position: "DF",
    number: 4,
    overall: 95,
  },
  {
    id: 8,
    name: "ramos",
    position: "DF",
    number: 4,
    overall: 93,
  },
  {
    id: 9,
    name: "marcelo",
    position: "DF",
    number: 12,
    overall: 90,
  },
  {
    id: 10,
    name: "alves",
    position: "DF",
    number: 2,
    overall: 91,
  },
  {
    id: 11,
    name: "neuer",
    position: "GK",
    number: 1,
    overall: 94,
  },
];

export const FORMATIONS = {
  "4-2-3-1": {
    1: { top: "90%", left: "50%", role: "GK" },
    2: { top: "75%", left: "10%", role: "LB" },
    3: { top: "75%", left: "35%", role: "CB" },
    4: { top: "75%", left: "65%", role: "CB" },
    5: { top: "75%", left: "90%", role: "RB" },
    6: { top: "55%", left: "25%", role: "CDM" },
    7: { top: "55%", left: "75%", role: "CDM" },
    8: { top: "40%", left: "50%", role: "CAM" },
    9: { top: "20%", left: "15%", role: "LW" },
    10: { top: "20%", left: "85%", role: "RW" },
    11: { top: "18%", left: "50%", role: "ST" },
  },
  "4-4-2": {
    1: { top: "90%", left: "50%", role: "GK" },
    2: { top: "75%", left: "15%", role: "LB" },
    3: { top: "75%", left: "38%", role: "CB" },
    4: { top: "75%", left: "62%", role: "CB" },
    5: { top: "75%", left: "85%", role: "RB" },
    6: { top: "50%", left: "20%", role: "LM" },
    7: { top: "50%", left: "40%", role: "CM" },
    8: { top: "50%", left: "60%", role: "CM" },
    9: { top: "50%", left: "80%", role: "RM" },
    10: { top: "25%", left: "35%", role: "ST" },
    11: { top: "25%", left: "65%", role: "ST" },
  },
  "4-3-3": {
    1: { top: "90%", left: "50%", role: "GK" },
    2: { top: "75%", left: "15%", role: "LB" },
    3: { top: "75%", left: "38%", role: "CB" },
    4: { top: "75%", left: "62%", role: "CB" },
    5: { top: "75%", left: "85%", role: "RB" },
    6: { top: "55%", left: "50%", role: "CDM" },
    7: { top: "45%", left: "30%", role: "CM" },
    8: { top: "45%", left: "70%", role: "CM" },
    9: { top: "25%", left: "15%", role: "LW" },
    10: { top: "25%", left: "85%", role: "RW" },
    11: { top: "20%", left: "50%", role: "ST" },
  },
  "3-5-2": {
    1: { top: "90%", left: "50%", role: "GK" },
    2: { top: "75%", left: "20%", role: "CB" },
    3: { top: "75%", left: "50%", role: "CB" },
    4: { top: "75%", left: "80%", role: "CB" },
    5: { top: "50%", left: "15%", role: "LM" },
    6: { top: "55%", left: "35%", role: "CDM" },
    7: { top: "55%", left: "65%", role: "CDM" },
    8: { top: "50%", left: "85%", role: "RM" },
    9: { top: "40%", left: "50%", role: "CAM" },
    10: { top: "20%", left: "35%", role: "ST" },
    11: { top: "20%", left: "65%", role: "ST" },
  },
};

export type FormationType = keyof typeof FORMATIONS;
