import { Position, MainPosition } from "@/types/position";

export const POSITION_CATEGORY_MAP: Record<Position, MainPosition> = {
  ST: "FW",
  CF: "FW",
  RF: "FW",
  LF: "FW",
  RW: "FW",
  LW: "FW",
  RS: "FW",
  LS: "FW",
  FW: "FW",
  CM: "MF",
  LCM: "MF",
  RCM: "MF",
  CDM: "MF",
  LDM: "MF",
  RDM: "MF",
  CAM: "MF",
  LCAM: "MF",
  RCAM: "MF",
  RM: "MF",
  LM: "MF",
  RAM: "MF",
  LAM: "MF",
  MF: "MF",
  CB: "DF",
  LCB: "DF",
  RCB: "DF",
  LB: "DF",
  RB: "DF",
  LWB: "DF",
  RWB: "DF",
  SW: "DF",
  DF: "DF",
  GK: "GK",
};
