import type { MatchRecord } from "./types";

/** UI 검증용 목업 (API 연동 전) */
export const MOCK_MATCH_RECORDS: MatchRecord[] = [
  {
    id: "m1",
    dateLabel: "2026. 3. 5.",
    opponentName: "바르셀로나",
    ourScore: 1,
    theirScore: 2,
    result: "loss",
    quarters: [
      { home: 2, away: 1 },
      { home: 0, away: 1 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e1",
        kind: "goal",
        quarter: 1,
        scorerName: "홍길동",
        assistName: "김철수",
        buildUpName: "이영희",
      },
      {
        id: "e2",
        kind: "conceded",
        quarter: 1,
        opponentLabel: "메시",
      },
      {
        id: "e3",
        kind: "goal",
        quarter: 2,
        scorerName: "박민수",
        assistName: "최지훈",
      },
    ],
  },
  {
    id: "m2",
    dateLabel: "2026. 3. 10.",
    opponentName: "AC 밀란",
    ourScore: 4,
    theirScore: 0,
    result: "win",
    quarters: [
      { home: 1, away: 0 },
      { home: 2, away: 0 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e4",
        kind: "goal",
        quarter: 1,
        scorerName: "정우",
        assistName: "한빛",
        buildUpName: "서준",
      },
    ],
  },
  {
    id: "m3",
    dateLabel: "2026. 3. 15.",
    opponentName: "인터밀란",
    ourScore: 2,
    theirScore: 2,
    result: "draw",
    quarters: [
      { home: 1, away: 1 },
      { home: 0, away: 0 },
      { home: 1, away: 1 },
      { home: 0, away: 0 },
    ],
    timeline: [],
  },
  {
    id: "m4",
    dateLabel: "2026. 3. 5.",
    opponentName: "바르셀로나",
    ourScore: 1,
    theirScore: 2,
    result: "loss",
    quarters: [
      { home: 2, away: 1 },
      { home: 0, away: 1 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e1",
        kind: "goal",
        quarter: 1,
        scorerName: "홍길동",
        assistName: "김철수",
        buildUpName: "이영희",
      },
      {
        id: "e2",
        kind: "conceded",
        quarter: 1,
        opponentLabel: "메시",
      },
      {
        id: "e3",
        kind: "goal",
        quarter: 2,
        scorerName: "박민수",
        assistName: "최지훈",
      },
    ],
  },
  {
    id: "m5",
    dateLabel: "2026. 3. 10.",
    opponentName: "AC 밀란",
    ourScore: 4,
    theirScore: 0,
    result: "win",
    quarters: [
      { home: 1, away: 0 },
      { home: 2, away: 0 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e4",
        kind: "goal",
        quarter: 1,
        scorerName: "정우",
        assistName: "한빛",
        buildUpName: "서준",
      },
    ],
  },
  {
    id: "m6",
    dateLabel: "2026. 3. 15.",
    opponentName: "인터밀란",
    ourScore: 2,
    theirScore: 2,
    result: "draw",
    quarters: [
      { home: 1, away: 1 },
      { home: 0, away: 0 },
      { home: 1, away: 1 },
      { home: 0, away: 0 },
    ],
    timeline: [],
  },
  {
    id: "m7",
    dateLabel: "2026. 3. 5.",
    opponentName: "바르셀로나",
    ourScore: 1,
    theirScore: 2,
    result: "loss",
    quarters: [
      { home: 2, away: 1 },
      { home: 0, away: 1 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e1",
        kind: "goal",
        quarter: 1,
        scorerName: "홍길동",
        assistName: "김철수",
        buildUpName: "이영희",
      },
      {
        id: "e2",
        kind: "conceded",
        quarter: 1,
        opponentLabel: "메시",
      },
      {
        id: "e3",
        kind: "goal",
        quarter: 2,
        scorerName: "박민수",
        assistName: "최지훈",
      },
    ],
  },
  {
    id: "m8",
    dateLabel: "2026. 3. 10.",
    opponentName: "AC 밀란",
    ourScore: 4,
    theirScore: 0,
    result: "win",
    quarters: [
      { home: 1, away: 0 },
      { home: 2, away: 0 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e4",
        kind: "goal",
        quarter: 1,
        scorerName: "정우",
        assistName: "한빛",
        buildUpName: "서준",
      },
    ],
  },
  {
    id: "m9",
    dateLabel: "2026. 3. 15.",
    opponentName: "인터밀란",
    ourScore: 2,
    theirScore: 2,
    result: "draw",
    quarters: [
      { home: 1, away: 1 },
      { home: 0, away: 0 },
      { home: 1, away: 1 },
      { home: 0, away: 0 },
    ],
    timeline: [],
  },
  {
    id: "m10",
    dateLabel: "2026. 3. 5.",
    opponentName: "바르셀로나",
    ourScore: 1,
    theirScore: 2,
    result: "loss",
    quarters: [
      { home: 2, away: 1 },
      { home: 0, away: 1 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e1",
        kind: "goal",
        quarter: 1,
        scorerName: "홍길동",
        assistName: "김철수",
        buildUpName: "이영희",
      },
      {
        id: "e2",
        kind: "conceded",
        quarter: 1,
        opponentLabel: "메시",
      },
      {
        id: "e3",
        kind: "goal",
        quarter: 2,
        scorerName: "박민수",
        assistName: "최지훈",
      },
    ],
  },
  {
    id: "m11",
    dateLabel: "2026. 3. 10.",
    opponentName: "AC 밀란",
    ourScore: 4,
    theirScore: 0,
    result: "win",
    quarters: [
      { home: 1, away: 0 },
      { home: 2, away: 0 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e4",
        kind: "goal",
        quarter: 1,
        scorerName: "정우",
        assistName: "한빛",
        buildUpName: "서준",
      },
    ],
  },
  {
    id: "m12",
    dateLabel: "2026. 3. 15.",
    opponentName: "인터밀란",
    ourScore: 2,
    theirScore: 2,
    result: "draw",
    quarters: [
      { home: 1, away: 1 },
      { home: 0, away: 0 },
      { home: 1, away: 1 },
      { home: 0, away: 0 },
    ],
    timeline: [],
  },
  {
    id: "m13",
    dateLabel: "2026. 3. 5.",
    opponentName: "바르셀로나",
    ourScore: 1,
    theirScore: 2,
    result: "loss",
    quarters: [
      { home: 2, away: 1 },
      { home: 0, away: 1 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e1",
        kind: "goal",
        quarter: 1,
        scorerName: "홍길동",
        assistName: "김철수",
        buildUpName: "이영희",
      },
      {
        id: "e2",
        kind: "conceded",
        quarter: 1,
        opponentLabel: "메시",
      },
      {
        id: "e3",
        kind: "goal",
        quarter: 2,
        scorerName: "박민수",
        assistName: "최지훈",
      },
    ],
  },
  {
    id: "m14",
    dateLabel: "2026. 3. 10.",
    opponentName: "AC 밀란",
    ourScore: 4,
    theirScore: 0,
    result: "win",
    quarters: [
      { home: 1, away: 0 },
      { home: 2, away: 0 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e4",
        kind: "goal",
        quarter: 1,
        scorerName: "정우",
        assistName: "한빛",
        buildUpName: "서준",
      },
    ],
  },
  {
    id: "m15",
    dateLabel: "2026. 3. 15.",
    opponentName: "인터밀란",
    ourScore: 2,
    theirScore: 2,
    result: "draw",
    quarters: [
      { home: 1, away: 1 },
      { home: 0, away: 0 },
      { home: 1, away: 1 },
      { home: 0, away: 0 },
    ],
    timeline: [],
  },
  {
    id: "m16",
    dateLabel: "2026. 3. 5.",
    opponentName: "바르셀로나",
    ourScore: 1,
    theirScore: 2,
    result: "loss",
    quarters: [
      { home: 2, away: 1 },
      { home: 0, away: 1 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e1",
        kind: "goal",
        quarter: 1,
        scorerName: "홍길동",
        assistName: "김철수",
        buildUpName: "이영희",
      },
      {
        id: "e2",
        kind: "conceded",
        quarter: 1,
        opponentLabel: "메시",
      },
      {
        id: "e3",
        kind: "goal",
        quarter: 2,
        scorerName: "박민수",
        assistName: "최지훈",
      },
    ],
  },
  {
    id: "m17",
    dateLabel: "2026. 3. 10.",
    opponentName: "AC 밀란",
    ourScore: 4,
    theirScore: 0,
    result: "win",
    quarters: [
      { home: 1, away: 0 },
      { home: 2, away: 0 },
      { home: 1, away: 0 },
      { home: 0, away: 0 },
    ],
    timeline: [
      {
        id: "e4",
        kind: "goal",
        quarter: 1,
        scorerName: "정우",
        assistName: "한빛",
        buildUpName: "서준",
      },
    ],
  },
  {
    id: "m18",
    dateLabel: "2026. 3. 15.",
    opponentName: "인터밀란",
    ourScore: 2,
    theirScore: 2,
    result: "draw",
    quarters: [
      { home: 1, away: 1 },
      { home: 0, away: 0 },
      { home: 1, away: 1 },
      { home: 0, away: 0 },
    ],
    timeline: [],
  },
];
