import type { Player } from "../_types/player";

// 실제 축구 선수 더미 데이터
export const allPlayers: Player[] = [
  {
    id: 1,
    name: "호날두",
    team: "포르투갈",
    value: "45골",
    image: "/images/player/img_player-1.png",
    position: "ST",
    backNumber: 7,
    ovr: 92,
    stats: {
      출장: 38,
      오버롤: 92,
      골: 45,
      어시: 12,
      기점: 57,
      클린시트: 0,
      주발: "R",
      승률: "68%",
      득점: 45,
      도움: 12,
      공격P: 57,
      MOM3: 15,
      MOM8: 28,
    },
    cumulativeStats: {
      출장: 250,
      오버롤: 92,
      골: 320,
      어시: 95,
      기점: 415,
      클린시트: 0,
      주발: "R",
      승률: "65%",
    },
  },
  {
    id: 2,
    name: "메시",
    team: "아르헨티나",
    value: "42골",
    image: "/images/player/img_player-2.png",
    position: "RW",
    backNumber: 10,
    ovr: 93,
    stats: {
      출장: 35,
      오버롤: 93,
      골: 42,
      어시: 21,
      기점: 63,
      클린시트: 0,
      주발: "L",
      승률: "72%",
      득점: 42,
      도움: 21,
      공격P: 63,
      MOM3: 18,
      MOM8: 32,
    },
    cumulativeStats: {
      출장: 280,
      오버롤: 93,
      골: 380,
      어시: 180,
      기점: 560,
      클린시트: 0,
      주발: "L",
      승률: "70%",
    },
  },
  {
    id: 3,
    name: "음바페",
    team: "프랑스",
    value: "38골",
    image: "/images/player/img_player-3.png",
    position: "LW",
    backNumber: 7,
    ovr: 91,
    stats: {
      출장: 34,
      오버롤: 91,
      골: 38,
      어시: 15,
      기점: 53,
      클린시트: 0,
      주발: "R",
      승률: "65%",
      득점: 38,
      도움: 15,
      공격P: 53,
      MOM3: 12,
      MOM8: 22,
    },
    cumulativeStats: {
      출장: 180,
      오버롤: 91,
      골: 200,
      어시: 85,
      기점: 285,
      클린시트: 0,
      주발: "R",
      승률: "62%",
    },
  },
  {
    id: 4,
    name: "홀란드",
    team: "노르웨이",
    value: "52골",
    image: "/images/player/img_player-4.png",
    position: "ST",
    backNumber: 9,
    ovr: 91,
    stats: {
      출장: 36,
      오버롤: 91,
      골: 52,
      어시: 8,
      기점: 60,
      클린시트: 0,
      주발: "L",
      승률: "70%",
      득점: 52,
      도움: 8,
      공격P: 60,
      MOM3: 20,
      MOM8: 35,
    },
    cumulativeStats: {
      출장: 150,
      오버롤: 91,
      골: 180,
      어시: 35,
      기점: 215,
      클린시트: 0,
      주발: "L",
      승률: "68%",
    },
  },
  {
    id: 5,
    name: "벨링엄",
    team: "잉글랜드",
    value: "25골",
    image: "/images/player/img_player-5.png",
    position: "CAM",
    backNumber: 5,
    ovr: 89,
    stats: {
      출장: 40,
      오버롤: 89,
      골: 25,
      어시: 18,
      기점: 43,
      클린시트: 0,
      주발: "R",
      승률: "62%",
      득점: 25,
      도움: 18,
      공격P: 43,
      MOM3: 10,
      MOM8: 18,
    },
    cumulativeStats: {
      출장: 120,
      오버롤: 89,
      골: 65,
      어시: 45,
      기점: 110,
      클린시트: 0,
      주발: "R",
      승률: "60%",
    },
  },
  {
    id: 6,
    name: "비니시우스",
    team: "브라질",
    value: "20골",
    image: "/images/player/img_player-6.png",
    position: "LW",
    backNumber: 7,
    ovr: 90,
    stats: {
      출장: 38,
      오버롤: 90,
      골: 20,
      어시: 22,
      기점: 42,
      클린시트: 0,
      주발: "R",
      승률: "67%",
      득점: 20,
      도움: 22,
      공격P: 42,
      MOM3: 8,
      MOM8: 15,
    },
    cumulativeStats: {
      출장: 160,
      오버롤: 90,
      골: 75,
      어시: 85,
      기점: 160,
      클린시트: 0,
      주발: "R",
      승률: "65%",
    },
  },
  {
    id: 7,
    name: "살라",
    team: "이집트",
    value: "28골",
    image: "/images/player/img_player-7.png",
    position: "RW",
    backNumber: 11,
    ovr: 89,
    stats: {
      출장: 36,
      오버롤: 89,
      골: 28,
      어시: 14,
      기점: 42,
      클린시트: 0,
      주발: "L",
      승률: "70%",
      득점: 28,
      도움: 14,
      공격P: 42,
      MOM3: 11,
      MOM8: 20,
    },
    cumulativeStats: {
      출장: 220,
      오버롤: 89,
      골: 180,
      어시: 90,
      기점: 270,
      클린시트: 0,
      주발: "L",
      승률: "68%",
    },
  },
  {
    id: 8,
    name: "데브라이너",
    team: "벨기에",
    value: "15골",
    image: "/images/player/img_player-8.png",
    position: "CM",
    backNumber: 17,
    ovr: 91,
    stats: {
      출장: 32,
      오버롤: 91,
      골: 15,
      어시: 28,
      기점: 43,
      클린시트: 0,
      주발: "R",
      승률: "75%",
      득점: 15,
      도움: 28,
      공격P: 43,
      MOM3: 14,
      MOM8: 25,
    },
    cumulativeStats: {
      출장: 200,
      오버롤: 91,
      골: 80,
      어시: 150,
      기점: 230,
      클린시트: 0,
      주발: "R",
      승률: "72%",
    },
  },
  {
    id: 9,
    name: "반다이크",
    team: "네덜란드",
    value: "5골",
    image: "/images/player/img_player-9.png",
    position: "CB",
    backNumber: 4,
    ovr: 90,
    stats: {
      출장: 38,
      오버롤: 90,
      골: 5,
      어시: 2,
      기점: 7,
      클린시트: 22,
      주발: "R",
      승률: "68%",
      득점: 5,
      도움: 2,
      공격P: 7,
      MOM3: 6,
      MOM8: 10,
    },
    cumulativeStats: {
      출장: 180,
      오버롤: 90,
      골: 18,
      어시: 8,
      기점: 26,
      클린시트: 95,
      주발: "R",
      승률: "65%",
    },
  },
  {
    id: 10,
    name: "쿠르투아",
    team: "벨기에",
    value: "0골",
    image: "/images/player/img_player-10.png",
    position: "GK",
    backNumber: 1,
    ovr: 90,
    stats: {
      출장: 40,
      오버롤: 90,
      골: 0,
      어시: 0,
      기점: 0,
      클린시트: 28,
      주발: "L",
      승률: "72%",
      득점: 0,
      도움: 0,
      공격P: 0,
      MOM3: 8,
      MOM8: 14,
    },
    cumulativeStats: {
      출장: 200,
      오버롤: 90,
      골: 0,
      어시: 1,
      기점: 1,
      클린시트: 120,
      주발: "L",
      승률: "70%",
    },
  },
];

// 카테고리에 맞는 value 표시
export const getPlayerValue = (player: Player, category: string) => {
  switch (category) {
    case "OVR":
      return `${player.ovr}`;
    case "출장수":
      return `${player.stats?.출장 || 0}경기`;
    case "득점":
      return `${player.stats?.득점 || 0}골`;
    case "도움":
      return `${player.stats?.도움 || 0}개`;
    case "기점":
      return `${player.stats?.기점 || 0}P`;
    case "공격P":
      return `${player.stats?.공격P || 0}P`;
    case "클린시트":
      return `${player.stats?.클린시트 || 0}회`;
    case "MOM3":
      return `${player.stats?.MOM3 || 0}회`;
    case "승률":
      return `${player.stats?.승률 || "0%"}`;
    default:
      return player.value;
  }
};

// 카테고리별 데이터 (9개 카테고리)
export const statsData: Record<string, Player[]> = {
  OVR: [...allPlayers].sort((a, b) => (b.ovr || 0) - (a.ovr || 0)),
  출장수: [...allPlayers].sort(
    (a, b) => (b.stats?.출장 || 0) - (a.stats?.출장 || 0),
  ),
  득점: [...allPlayers].sort(
    (a, b) => (b.stats?.득점 || 0) - (a.stats?.득점 || 0),
  ),
  도움: [...allPlayers].sort(
    (a, b) => (b.stats?.도움 || 0) - (a.stats?.도움 || 0),
  ),
  기점: [...allPlayers].sort(
    (a, b) => (b.stats?.기점 || 0) - (a.stats?.기점 || 0),
  ),
  공격P: [...allPlayers].sort(
    (a, b) => (b.stats?.공격P || 0) - (a.stats?.공격P || 0),
  ),
  클린시트: [...allPlayers].sort(
    (a, b) => (b.stats?.클린시트 || 0) - (a.stats?.클린시트 || 0),
  ),
  MOM3: [...allPlayers].sort(
    (a, b) => (b.stats?.MOM3 || 0) - (a.stats?.MOM3 || 0),
  ),
  승률: [...allPlayers].sort((a, b) => {
    const aRate = parseInt((a.stats?.승률 || "0%").replace("%", "")) || 0;
    const bRate = parseInt((b.stats?.승률 || "0%").replace("%", "")) || 0;
    return bRate - aRate;
  }),
};
